spring.application.name=payguard
spring.datasource.url=jdbc:postgresql://localhost:5432/payguard
spring.datasource.username=postgres
spring.datasource.password=tanaka

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true